Added new FAQs and resolved 'content' labeled FAQs
conda-incubator/conda-dot-org pull request #137
Opened 2023-05-17 17:57 UTC by Pinak-Datta

### Description
This PR resolves the following:

- Added new FAQs to enhance the FAQ section.
- Resolved FAQs labeled as 'content' on GitHub.
- Improved the overall content and information provided in the FAQs.

Initial problem: The FAQ section was lacking certain questions and answers, and there were unresolved FAQs labeled as 'content' on GitHub.

Choices to be aware of:

- Ensure the new FAQs are comprehensive and cover common user queries.
- Verify that the resolved FAQs accurately address the issues mentioned in the 'content' labeled FAQs.
- Review and test the changes thoroughly before merging the PR.

2023-05-19 01:15 UTC, kathatherine requested changes
Lots of great stuff here, Pinak. Thanks for getting going on this so quickly!

I'm sure everyone else will have opinions on how we're approaching talking about conda here. I've left you some questions and comments to consider. @travishathaway, @beeankha, @jezdez, @jaimergp, @tnabtaf, would also love your input, if you have time.

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
>  [Conda-forge](https://conda-forge.org/) is a [community-led GitHub organization](https://github.com/conda-forge) that provides access to thousands of conda package recipes. All of these recipes are o
I know this isn't your addition, Pinak, but we should be sure we're consistent with the conda-forge naming.

@jaimergp, is it supposed to always be lowercase, or is capitalizing at the beginning of a sentence fine?

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
> +- [**Conda packages**](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html): These are compressed tarballs or .conda files containing system-level libraries, modules, exe
A newer user probably won't know what a prefix is.

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
> +- [**Conda environments**](https://docs.conda.io/docs/using/envs.html#:~:text=A%20conda%20environment%20is%20a,NumPy%201.6%20for%20legacy%20testing.): Conda environments are directories that contain
Are you meaning to have this URL highlight words on the other end?

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
> +- **Conda channels**: Conda channels are locations where packages are stored and serve as the base for hosting and managing packages. They are hosted on the [Anaconda.org](https://anaconda.org/) plat
Is Anaconda.org the only channel host?

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
> +- **Miniconda and Anaconda**: These are distributions that include Conda as the package manager. [Miniconda](https://docs.conda.io/en/latest/miniconda.html) provides a minimal installation, while [An
There's also Micromamba, though I know you're talking about conda here.

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
> +- **Conda, the tool (Mamba)**: [Mamba](https://mamba.readthedocs.io/en/latest/installation.html) is a high-performance, drop-in replacement for Conda, written in C++, offering faster package manageme
Did you mean to say "Mamba, the tool" here? It's an alternative to conda, but I didn't think you needed conda to use Mamba and this entry kind of makes it seem like you do.

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
> +You can find more about this [here](https://conda.org/community#the-many-meanings-of-conda)
This sentence needs a period at the end.

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
> +1. **Exporting the environment:** With conda, you can export the environment to a YAML file that contains a list of all the packages and their versions. Open your terminal or command prompt, activate
Let's go with "your environment" instead of "the environment" throughout. Makes it a little less formal sounding.

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
> +2. **Sharing the environment file:** Once you have the `environment.yml` file, you can share it with others through various means, such as email, file sharing services, or version control systems lik
Doesn't the environment.yml file include information about dependencies in it?

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
> +This command reads the `environment.yml` file and recreates the environment with the same package versions and dependencies. The person needs to have conda or mamba installed on their system.
Yeah, go with "you" instead of "the person". We tend to use 2nd-person throughout our writing to decrease the formality.

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
> +Replace `<environment-name>` with the name of the shared environment.
There should be a newline after this line. Otherwise, it will end up in the same paragraph as the line below.

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
> +Remember that channels play a crucial role in environment replication. If the environment relies on packages from specific channels other than the defaults, the other person might need to add those c
"If your environment relies on..., you might need to..."

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
> +For step-by-step guidance on setting up your package, defining dependencies, handling different platforms, and more, you can checkout the [documentation for conda-build](https://docs.conda.io/project
"check out" should be two words here

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
> +For step-by-step guidance on setting up your package, defining dependencies, handling different platforms, and more, you can checkout the [documentation for conda-build](https://docs.conda.io/project
And you've got a space between the last word and the period at the end of the sentence that shouldn't be there.

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
> +If you need further assistance or have specific questions related to creating conda packages, I recommend visiting the [conda community page](https://conda.org/community).
Putting "I" in here when it's not a blog is a little _too_ formal. Just change "I recommend visiting" to "visit".

2023-05-19 01:15 UTC, kathatherine commented on learn/faq.md
> +The Conda community is a vibrant and diverse group of users and developers who utilize the Conda package management system for creating, managing, and distributing software environments. The communit
Not just conda.

2023-05-22 15:54 UTC, beeankha commented on learn/faq.md
> +Yes, conda can be used to manage non-Python packages. While conda is widely known for its capabilities in managing Python packages, it is not limited to Python alone. conda supports package managemen
```suggestion
Yes, conda can be used to manage non-Python packages. While conda is widely known for its capabilities in managing Python packages, it is not limited to Python alone. Conda supports package management for multiple programming languages, including R, Java, C/C++, and more. It allows you to install, manage, and update packages from different languages, ensuring consistent package installations and dependencies across your projects. 
```

2023-05-22 15:54 UTC, beeankha commented on learn/faq.md
> +[conda-forge](https://conda-forge.org/) is a [community-led GitHub organization](https://github.com/conda-forge) that provides access to thousands of conda package recipes. All of these recipes are o
```suggestion
[Conda-forge](https://conda-forge.org/) is a [community-led GitHub organization](https://github.com/conda-forge) that provides access to thousands of conda package recipes. All of these recipes are open source and can be installed with the conda package manager by specifying conda-forge as the channel.
```

2023-05-22 15:54 UTC, beeankha commented on learn/faq.md
> +- **conda as a tool**: conda is an open-source, cross-platform package manager used for managing software packages.
```suggestion
- **Conda as a tool**: Conda is an open-source, cross-platform package manager used for managing software packages.
```

2023-05-22 15:54 UTC, beeankha commented on learn/faq.md
> +- [**conda packages**](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html): These are compressed tarballs or .conda files containing system-level libraries, modules, exe
```suggestion
- [**Conda packages**](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html): These are compressed tarballs or .conda files containing system-level libraries, modules, executables, and metadata, installed into the designated prefix.
```

2023-05-22 15:54 UTC, beeankha commented on learn/faq.md
> +- [**conda environments**](https://docs.conda.io/docs/using/envs.html#:~:text=A%20conda%20environment%20is%20a,NumPy%201.6%20for%20legacy%20testing.): conda environments are directories that contain
```suggestion
- [**Conda environments**](https://docs.conda.io/docs/using/envs.html#:~:text=A%20conda%20environment%20is%20a,NumPy%201.6%20for%20legacy%20testing.): Conda environments are directories that contain specific collections of conda packages installed for a particular project or use case.
```

2023-05-22 15:54 UTC, beeankha commented on learn/faq.md
> +- **conda channels**: conda channels are locations where packages are stored and serve as the base for hosting and managing packages. They are hosted on the [Anaconda.org](https://anaconda.org/) plat
```suggestion
- **Conda channels**: Conda channels are locations where packages are stored and serve as the base for hosting and managing packages. They are hosted on the [Anaconda.org](https://anaconda.org/) platform.
```

2023-05-22 15:54 UTC, beeankha commented on learn/faq.md
> +- **conda, the package format**: conda can also refer to the package format itself, which is an archive containing programs and metadata needed by package managers.
```suggestion
- **Conda, the package format**: Conda can also refer to the package format itself, which is an archive containing programs and metadata needed by package managers.
```

2023-05-22 15:54 UTC, beeankha commented on learn/faq.md
> +- **conda community**: The conda community includes channels like [conda-forge](https://conda-forge.org/) and [bioconda](https://bioconda.github.io/), which provide additional packages and resources.
```suggestion
- **Conda community**: The conda community includes channels like [conda-forge](https://conda-forge.org/) and [bioconda](https://bioconda.github.io/), which provide additional packages and resources.
```

2023-05-22 15:54 UTC, beeankha commented on learn/faq.md
> +- **conda, the tool (Mamba)**: [Mamba](https://mamba.readthedocs.io/en/latest/installation.html) is a high-performance, drop-in replacement for conda, written in C++, offering faster package manageme
```suggestion
- **Conda, the tool (Mamba)**: [Mamba](https://mamba.readthedocs.io/en/latest/installation.html) is a high-performance, drop-in replacement for conda, written in C++, offering faster package management.
```

2023-05-22 15:54 UTC, beeankha commented on learn/faq.md
> +- [**conda Package Specification**](https://conda.io/projects/conda-build/en/latest/resources/package-spec.html): This refers to the contents of an extracted package, regardless of the compression fo
```suggestion
- [**Conda Package Specification**](https://conda.io/projects/conda-build/en/latest/resources/package-spec.html): This refers to the contents of an extracted package, regardless of the compression format used.
```

2023-05-22 15:54 UTC, beeankha commented on learn/faq.md
> +On the other hand, conda is a powerful package and environment manager that can install much more than just Python libraries. With conda, users can install entire software stacks (while remaining ass
```suggestion
On the other hand, conda is a powerful package and environment manager that can install much more than just Python libraries. With conda, users can install entire software stacks (while remaining assured that all dependencies are accounted for and resolved), as well as R programs and libraries, Node.js, Java programs, C++ programs and libraries, Perl programs, and more. Conda has an environment management system that allows users to have all of these installed across multiple different environments; it also enables installation of complex software stacks on a system without needing root privileges, due to it being able to do all of these software and package installations in an isolated, userspace manner.
```

2023-05-22 15:54 UTC, beeankha commented on learn/faq.md
> +This command reads the `environment.yml` file and recreates the environment with the same package versions and dependencies. You need to have conda or mamba installed on their system.
```suggestion
This command reads the `environment.yml` file and recreates the environment with the same package versions and dependencies. The person building an environment from this file needs to have conda or mamba installed on their system.
```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +
```suggestion

```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +1. **Exporting the environment:** With conda, you can export the environment to a YAML file that contains a list of all the packages and their versions. Open the terminal or command prompt, activate
```suggestion

1. **Exporting the environment:** With conda, you can export the environment to a YAML file that contains a list of all the packages and their versions. Open the terminal or command prompt, activate the environment you want to share, and use the following command:

```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
>  Note: If using mamba instead of conda, the command will be:
```suggestion

Note: If using mamba instead of conda, the command will be:

```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +For step-by-step guidance on setting up the package, defining dependencies, handling different platforms, and more, you can check out the [documentation for conda-build](https://docs.conda.io/project
```suggestion
For step-by-step guidance on setting up packages, defining dependencies, handling different platforms, and more, you can check out the [documentation for conda-build](https://docs.conda.io/projects/conda-build/en/stable/user-guide/tutorials/building-conda-packages.html).
```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +To create a conda package for the project, you can start by referring to the official documentation provided by [conda-build](https://github.com/conda/conda-build).
```suggestion
To create a conda package for your project, you can start by referring to the official documentation provided by [conda-build](https://github.com/conda/conda-build).
```

Your is fine here. :)

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +If you need further assistance or have specific questions related to creating conda packages, visit [conda community page](https://conda.org/community).
```suggestion
If you need further assistance or have specific questions related to creating conda packages, visit the [conda community page](https://conda.org/community).
```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +## How is the Conda community organized?
```suggestion
## How is the conda community organized?
```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +The Conda community is a vibrant and diverse group of users and developers who utilize Conda, a popular package management system, for creating, managing, and distributing software environments. The
```suggestion
The conda community is a vibrant and diverse group of users and developers who utilize conda, a popular package management system, for creating, managing, and distributing software environments. The conda community consists of various sub-communities that play an important role in supporting and extending the functionality of conda. Some of these communities include:
```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +- [Conda Forge](https://conda-forge.org/): A community-led collection of recipes, build infrastructure, and packages for Conda. It provides a wide range of community-maintained packages that can be e
```suggestion
- [conda-forge](https://conda-forge.org/): A community-led collection of recipes, build infrastructure, and packages for conda. It provides a wide range of community-maintained packages that can be easily installed using conda.
```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +- [Bioconda](https://bioconda.github.io/): A specialized community for bioinformatics software packages. Bioconda offers a comprehensive collection of bioinformatics tools and libraries that can be e
```suggestion
- [Bioconda](https://bioconda.github.io/): A specialized community for bioinformatics software packages. Bioconda offers a comprehensive collection of bioinformatics tools and libraries that can be easily managed with conda.
```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +- [Micromamba](https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html): A lightweight, fast, and pure C++based alternative to Conda. Micromamba is designed to provide a streamlined package
```suggestion
- [Micromamba](https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html): A lightweight, fast, and pure C++ based alternative to conda. Micromamba is designed to provide a streamlined package management experience and is compatible with conda environments and packages.
```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +These communities actively contribute to the Conda ecosystem, providing additional packages, resources, and support for users and developers.
```suggestion
These communities actively contribute to the conda ecosystem, providing additional packages, resources, and support for users and developers.
```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +
```suggestion

```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +To install a non-Python package, you can use the following command:
```suggestion
To install a non-Python package, you can use the following command:

```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +By default, Conda will search for the package in the default channels. However, you can also obtain non-Python packages from other channels apart from conda-forge. For example, you can specify a diff
```suggestion

By default, Conda will search for the package in the default channels. However, you can also obtain non-Python packages from other channels apart from conda-forge. For example, you can specify a different channel using the -c flag:

```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +For example, to install a non-Python package like gcc for C/C++ programming language, from the conda-forge channel, you can run:
```suggestion

For example, to install a non-Python package like gcc for C/C++ programming language, from the conda-forge channel, you can run:

```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +Similarly, you can use conda to manage packages for other languages such as R, Java, or any other supported language. Just replace `<package-name> `with the specific package you want to install.
```suggestion

Similarly, you can use conda to manage packages for other languages such as R, Java, or any other supported language. Just replace `<package-name> `with the specific package you want to install.
```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +
```suggestion

```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +This command exports the environment to an `environment.yml` file.
```suggestion

This command exports the environment to an `environment.yml` file.
```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +3. **Creating the environment from the file:** To create an identical environment on another machine, the other person can use the following command in their terminal or command prompt:
```suggestion
3. **Creating the environment from the file:** To create an identical environment on another machine, the other person can use the following command in their terminal or command prompt:

```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +This command reads the `environment.yml` file and recreates the environment with the same package versions and dependencies. The person building an environment from this file needs to have conda or m
```suggestion

This command reads the `environment.yml` file and recreates the environment with the same package versions and dependencies. The person building an environment from this file needs to have conda or mamba installed on their system.
```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +4. **Activating the shared environment:** After the environment is successfully created, the other person can activate it with:
```suggestion

4. **Activating the shared environment:** After the environment is successfully created, the other person can activate it with:

```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +or
```suggestion

or

```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +Replace `<environment-name>` with the name of the shared environment.
```suggestion

Replace `<environment-name>` with the name of the shared environment.
```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +Remember that channels play a crucial role in environment replication. If your environment relies on packages from specific channels other than the defaults, then you might need to add those channels
```suggestion
Remember that channels play a crucial role in environment replication. If your environment relies on packages from specific channels other than the defaults, then you might need to add those channels using:

```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +or
```suggestion

or

```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +before creating the environment from the YAML file.
```suggestion

before creating the environment from the YAML file.
```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +To contact us, please refer to the [Community Page](https://conda.org/community#how-to-reach-us).
```suggestion
To contact us, please refer to the [Community Page](https://conda.org/community#how-to-reach-us).
```

2023-06-03 17:25 UTC, kathatherine commented on learn/faq.md
> +
```suggestion

```

2023-06-03 17:28 UTC, kathatherine reviewed
Thanks for all your work on this! I applied some formatting changes real quick. You'll want to `git pull` in those changes if you make any more edits on your fork. I want to remind people that this exists at the conda.org community meeting on Wednesday and give them a chance to look it over before we merge in.

2023-06-04 07:05 UTC, Pinak-Datta commented
> Thanks for all your work on this! I applied some formatting changes real quick. You'll want to `git pull` in those changes if you make any more edits on your fork. I want to remind people that this exists at the conda.org community meeting on Wednesday and give them a chance to look it over before we merge in.

Ok, Thanks!

2023-06-08 11:59 UTC, travishathaway commented
I noticed this branch was out of sync with main in some weird ways. I made a lot of manual updates to make sure everything would be okay after the merge.

2023-06-08 13:05 UTC, travishathaway approved these changes
LGTM 🚀

2023-06-08 15:30 UTC, kathatherine approved these changes

2023-06-08 15:30 UTC, merged

2023-06-08 15:34 UTC, kathatherine commented
@Pinak-Datta Congrats on your first merge in the repo! If you could list the GitHub tickets that this PR closes by number in the description at the top of this PR, that'd be great. That way we can make sure any open tickets are closed properly.

2023-06-08 17:38 UTC, Pinak-Datta commented
> @Pinak-Datta Congrats on your first merge in the repo! If you could list the GitHub tickets that this PR closes by number in the description at the top of this PR, that'd be great. That way we can make sure any open tickets are closed properly.
Done adding the list of tickets that this PR Closes.