Added where can i find help? to faq
conda-incubator/conda-dot-org pull request #84
Opened 2023-04-03 16:35 UTC by ankushbhardwaj408

Hi @kathatherine i have added the "Where can i find help?" to the faq section. Issue #53 
![Screenshot 2023-04-03 220154](https://user-images.githubusercontent.com/93874580/229572050-940a0b5a-7fea-4623-b6ea-6ad62e7f285d.png)

2023-04-04 10:39 UTC, travishathaway commented
Hi @ankushbhardwaj408,

Thanks for taking the initiative to pick up this issue.

I have a suggestion to improve the answer you submitted. On the community page, we have a "[How to reach us](https://conda-dot-org.netlify.app/community#how-to-reach-us)" section. Could you please link to that in your answer? Not only does it list the element chat rooms but also links to the conda Discourse server and our GitHub organizations.

2023-04-04 10:48 UTC, ankushbhardwaj408 commented
HI @travishathaway 
Thanks for the suggestions. I am working on it.

2023-04-04 15:25 UTC, ankushbhardwaj408 commented
HI @travishathaway i have made the suggested changes. Please review it. #84 
![Screenshot 2023-04-04 205258](https://user-images.githubusercontent.com/93874580/229840657-1d4a5c35-876f-48fb-9ee2-836e49991858.png)

2023-04-05 05:49 UTC, travishathaway commented on learn/faq.md
> +If you want some help you can reach out to us and get the necessary help.
```suggestion
If you need help with any aspect of the conda ecosystem, feel free to reach out to us via any of our online channels.
```

2023-04-05 05:50 UTC, travishathaway commented on learn/faq.md
> +Here are the social profiles of conda : [Element](https://app.element.io/#/room/#conda_conda:gitter.im),  [Discourse](https://conda.discourse.group/), [Github](https://github.com/conda-incubator).
```suggestion
```

2023-04-05 05:51 UTC, travishathaway commented on learn/faq.md
> +For more information [visit](http://localhost:3000/community#how-to-reach-us) here.
```suggestion
For more information read [How to reach us](/community#how-to-reach-us) on the [Community](/community) page.
```

2023-04-05 05:53 UTC, travishathaway requested changes
Hi @ankushbhardwaj408,

Please see my suggestions for improvement.

Please never use "https://localhost" links on any page for this website. This will not work. Instead, just use the absolute path (e.g. "/community").

2023-04-05 06:04 UTC, ankushbhardwaj408 commented
Thanks @travishathaway for the suggestions.

2023-04-05 09:22 UTC, travishathaway commented on learn/faq.md
> +For more information read [How to reach us](https://conda-dot-org.netlify.app/community/#how-to-reach-us) on the [Community](https://conda-dot-org.netlify.app/community) page.
```suggestion
For more information, read [How to reach us](https://conda-dot-org.netlify.app/community/#how-to-reach-us) on the [Community](https://conda-dot-org.netlify.app/community) page.
```

2023-04-05 09:24 UTC, travishathaway commented on learn/faq.md
> +For more information, read [How to reach us](https://conda-dot-org.netlify.app/community/#how-to-reach-us) on the [Community](https://conda-dot-org.netlify.app/community) page.
```suggestion
For more information, read [How to reach us](/community/#how-to-reach-us) on the [Community](/community) page.
```

2023-04-05 09:28 UTC, travishathaway approved these changes

2023-04-05 09:28 UTC, merged